BASICS OF PYTHON

In [ ]:
#Variable
a=10
print("Iam,",a,"years old")

Iam, 10 years old


In [ ]:
#Operations of two vaiables
a=int(input("enter a value"))
b=int(input("enter b value"))
print("difference",a-b)
print("sum is",a+b)
print("product is",a*b)
print("Quotient is",a/b)
print("remainder is",a%b)
print("Power of a to b is",a**b)

enter a value100
enter b value10
difference 90
sum is 110
product is 1000
Quotient is 10.0
remainder is 0
Power of a to b is 100000000000000000000


In [ ]:
#take a num from the user salary is the salary is more than 50000 there is a 10% tax print his final salary
salary=int(input("enter salary"))
if ( salary <50000):
  print("no tax ")
else:
  print("tax ",salary-salary*0.1)

enter salary14234
no tax 


In [ ]:
#get the saalry frim the user if the salary is more than or eqaual to 50000 apply 10% tax deduction if the salary is lessthan 50000 apply 5% tax if the salary is morethan 70000apply 12% tax if salary exits 1l print u r promoted tp nxt level
salary=int(input("Enter salary"))
if(salary<50000):
  print("Salary is",salary-salary*0.05)
elif(salary<70000):
  print("Salary is",salary-salary*0.1)
elif(salary<100000):
  print("Salary is",salary-salary*0.12)
else:
  print("You are promoted")

Enter salary64000
Salary is 57600.0


In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
n=int(input("Enter number"))
for i in range(1,21):
  print(n," x ",i, "=", n*i)

Enter number7
7  x  1 = 7
7  x  2 = 14
7  x  3 = 21
7  x  4 = 28
7  x  5 = 35
7  x  6 = 42
7  x  7 = 49
7  x  8 = 56
7  x  9 = 63
7  x  10 = 70
7  x  11 = 77
7  x  12 = 84
7  x  13 = 91
7  x  14 = 98
7  x  15 = 105
7  x  16 = 112
7  x  17 = 119
7  x  18 = 126
7  x  19 = 133
7  x  20 = 140


In [ ]:
n=int(input("enter number"))
i=1
while(i!=11):
  print(n,"x",i,"=",n*i)
  i=i+1

enter number12
12 x 1 = 12
12 x 2 = 24
12 x 3 = 36
12 x 4 = 48
12 x 5 = 60
12 x 6 = 72
12 x 7 = 84
12 x 8 = 96
12 x 9 = 108
12 x 10 = 120


In [ ]:
PUBG=["M762","AKM","MG3","DP-28","M24","Kar98","Mosin"]
PUBG.append("SRL")
PUBG.insert(7,"SKS")
print("SNIPPERS:",PUBG[4:7])
print("LIGHT MACHINE GUNS:",PUBG[2:4])
print("AR:",PUBG[0:2])
print("DMR:",PUBG[8:10])
PUBG.append("UMP")
print(PUBG)
PUBG.remove("UMP")
print(PUBG)

SNIPPERS: ['M24', 'Kar98', 'Mosin']
LIGHT MACHINE GUNS: ['MG3', 'DP-28']
AR: ['M762', 'AKM']
DMR: ['SRL']
['M762', 'AKM', 'MG3', 'DP-28', 'M24', 'Kar98', 'Mosin', 'SKS', 'SRL', 'UMP']
['M762', 'AKM', 'MG3', 'DP-28', 'M24', 'Kar98', 'Mosin', 'SKS', 'SRL']


In [ ]:
PUBG=["M762","AKM","MG3","DP-28","M24","Kar98","Mosin"]
PUBG.append("SRL")
print(PUBG)

['M762', 'AKM', 'MG3', 'DP-28', 'M24', 'Kar98', 'Mosin', 'SRL']


In [ ]:
#create a list of integers-10 elements print their squares ,save this squares in a new lsit
l=[2,6,9,11,15,21,25,34,42,50]
l1=[]
for i in l:
  l1.append(i*i)
print(l1)


[4, 36, 81, 121, 225, 441, 625, 1156, 1764, 2500]


In [ ]:
#newlsit = [output for]
#list comprehension
l=[2,6,9,11,15,21,25,34,42,50]
l1=[i*i for i in l]
print(l1)


[4, 36, 81, 121, 225, 441, 625, 1156, 1764, 2500]


In [ ]:
#squares less than 25
l=[2,6,9,11,15,21,25,34,42,50]
l1=[i*i for i in l if i<25]
print(l1)

[4, 36, 81, 121, 225, 441]


In [ ]:
#squares less than 25
l=[2,6,9,11,15,21,25,34,42,50]
l1=[i*i if i<25 else "x" for i in l]
print(l1)

[4, 36, 81, 121, 225, 441, 'x', 'x', 'x', 'x']


In [ ]:
# take the salary from the user if salary is less than 50k 10% tax otherwise 15% tax
salary=int(input("enter salary"))
aftertax=(salary-salary*0.1 if (salary<50000) else (salary- salary*0.15))
print(aftertax)

enter salary52103
44287.55


In [ ]:
# take the salary from the list if salary is less than 50k 10% tax otherwise 15% tax
salary=[78000,52000,36000,12000]
aftertax=[i-i*0.1 if i<50000 else i-i*0.15 for i in salary]
print(aftertax)

[66300.0, 44200.0, 32400.0, 10800.0]


In [ ]:
#Dictionery
dict1={"Tournament":"IPL",1:"CSK",2:"GT",3:"RPS"}
print(dict1)

{'Tournament': 'IPL', 1: 'CSK', 2: 'GT', 3: 'RPS'}


In [ ]:
#print keys
dict1={"Tournament":"IPL",1:"CSK",2:"GT",3:"RPS"}
print(dict1.keys())

dict_keys(['Tournament', 1, 2, 3])


In [ ]:
#print values
dict1={"Tournament":"IPL",1:"CSK",2:"GT",3:"RPS"}
print(dict1.values())

dict_values(['IPL', 'CSK', 'GT', 'RPS'])


In [ ]:
#print particular key value
dict1={"Tournament":"IPL",1:"CSK",2:"GT",3:"RPS"}
print(dict1["Tournament"])

IPL


In [ ]:
#print details
dict2={"dept":"CSE","details":{"year":"II","sec":"D","count":71}}
print("year is",dict2["details"]["year"])
print("section is",dict2["details"]["sec"])
print("count is",dict2["details"]["count"])

year is II
section is D
count is 71


In [ ]:
#ZIP in dictonery
guns=["M416","M762","UMP","UZI"]
ammo=[5.56,7.16,45,9]
new_dict=dict(zip(guns,ammo))
print(new_dict)

{'M416': 5.56, 'M762': 7.16, 'UMP': 45, 'UZI': 9}


In [ ]:
#ZIP
guns=["M416","M762","UMP","UZI"]
ammo=[5.56,7.16,45,9]
new=zip(guns,ammo)
for i in new:
  print(i)


('M416', 5.56)
('M762', 7.16)
('UMP', 45)
('UZI', 9)


In [ ]:
import numpy as np
A=np.array([1,2,3,4]) #1d Array
print(A.ndim)
print(A.shape)

1
(4,)


In [ ]:
#2d Array
import numpy as np
A=np.array([[1,2,3,4],[13,14,15,16],
            [5,6,7,8],[17,18,19,20],
            [9,10,11,12],[21,22,23,24]])
print(A.ndim)
print(A.shape)
print(A)

2
(6, 4)
[[ 1  2  3  4]
 [13 14 15 16]
 [ 5  6  7  8]
 [17 18 19 20]
 [ 9 10 11 12]
 [21 22 23 24]]


In [ ]:
A=np.array([[[1,2,3,4],[5,6,7,8]]]) #3d Array
print(A.ndim)
print(A.shape)
print(A)

3
(1, 2, 4)
[[[1 2 3 4]
  [5 6 7 8]]]


In [ ]:
A=np.zeros((2,4,3))
print(A)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
A=np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
A=np.arange(1,10)
print(A)
print(type(A))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers that are divisible by 8 using arange function btw 1 and 1000
A=np.arange(8,1001,8)
print(A)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


LINESPACE : spliting a range into n numbers with common differences

> Indented block

> Indented block





In [ ]:
A=np.linspace(51,65,100)
print(A)

[51.         51.14141414 51.28282828 51.42424242 51.56565657 51.70707071
 51.84848485 51.98989899 52.13131313 52.27272727 52.41414141 52.55555556
 52.6969697  52.83838384 52.97979798 53.12121212 53.26262626 53.4040404
 53.54545455 53.68686869 53.82828283 53.96969697 54.11111111 54.25252525
 54.39393939 54.53535354 54.67676768 54.81818182 54.95959596 55.1010101
 55.24242424 55.38383838 55.52525253 55.66666667 55.80808081 55.94949495
 56.09090909 56.23232323 56.37373737 56.51515152 56.65656566 56.7979798
 56.93939394 57.08080808 57.22222222 57.36363636 57.50505051 57.64646465
 57.78787879 57.92929293 58.07070707 58.21212121 58.35353535 58.49494949
 58.63636364 58.77777778 58.91919192 59.06060606 59.2020202  59.34343434
 59.48484848 59.62626263 59.76767677 59.90909091 60.05050505 60.19191919
 60.33333333 60.47474747 60.61616162 60.75757576 60.8989899  61.04040404
 61.18181818 61.32323232 61.46464646 61.60606061 61.74747475 61.88888889
 62.03030303 62.17171717 62.31313131 62.45454545 62.59

In [ ]:
#set operations
s1={1,2,3,4,5}
s2={4,5,6,7,8}
#union
print(s1.union(s2))
#intersection
print(s1.intersection(s2))
#difference
print(s1.difference(s2))
#symmetric_difference
print(s1.symmetric_difference(s2))
#subset
print(s1.issubset(s2))
#superset
print(s1.issuperset(s2))
#disjoint
print(s1.isdisjoint(s2))

{1, 2, 3, 4, 5, 6, 7, 8}
{4, 5}
{1, 2, 3}
{1, 2, 3, 6, 7, 8}
False
False
False


In [ ]:
#tuples
t=(1,2,3,4,5)
print(t)
#concat
t1=(1,2,3)+(4,5,6,3)
print(t1)
#lenght
print(len(t))
#repetition
t2=("hi! ")*4
print(t2)
#in
print(3 in t1)
#index
print(t[0])
print(t[0:4])
#updating tuple using list
tl=list(t)
tl[1]=55
t=tuple(tl)
print(t)
#type
print(type(t))
#count
print(t.count(5))
#index
print(t.index(5))


(1, 2, 3, 4, 5)
(1, 2, 3, 4, 5, 6, 3)
5
hi! hi! hi! hi! 
True
1
(1, 2, 3, 4)
(1, 55, 3, 4, 5)
<class 'tuple'>
1
4


In [ ]:
a=[2,4,5,12,34,1,3,5]
a.sort()
print(a)

[1, 2, 3, 4, 5, 5, 12, 34]


In [ ]:
a=[2,4,5,12,34,1,3]
b=sorted(a)
print(b)

[1, 2, 3, 4, 5, 12, 34]
