In [ ]:
import numpy as np

In [ ]:
import numpy as np
a=np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np
a=np.linspace(1,17,12).reshape(3,4)
print(a)

[[ 1.          2.45454545  3.90909091  5.36363636]
 [ 6.81818182  8.27272727  9.72727273 11.18181818]
 [12.63636364 14.09090909 15.54545455 17.        ]]


In [ ]:
b=np.array([34,45,63,22,17,12,21,67]).reshape(2,2,2)
print(b)

[[[34 45]
  [63 22]]

 [[17 12]
  [21 67]]]


resize:
chnages th eshape of original array
reshape:
changes needs saving in another variable

In [ ]:
b=np.array([34,45,63,22,17,12,21,67])
b.resize(2,2,2)
print(b)

[[[34 45]
  [63 22]]

 [[17 12]
  [21 67]]]


In [ ]:
#subtraction of lists
#error
a=np.array([21,34,56,71])
b=np.array([2,4,5,3])
print(a-b)

[19 30 51 68]


In [ ]:
#occurs error due to lists
a=[21,34,56,71]
b=[2,4,5,3]
print(a-b)

TypeError: unsupported operand type(s) for -: 'list' and 'list'

list will throw an error while arrays iterate themselves

In [ ]:
#addition of an array
a=np.array([21,34,56,71])
b=np.array([2,4,5,3])
print(a+b)

[23 38 61 74]


In [ ]:
#one to one multiplication
a=np.array([21,34,56,71]).reshape(2,2)
b=np.array([2,4,5,3]).reshape(2,2)
print(a)
print(b)
print(a*b)

[[21 34]
 [56 71]]
[[2 4]
 [5 3]]
[[ 42 136]
 [280 213]]


In [ ]:
#matrix multiplication
a=np.array([21,34,56,71]).reshape(2,2)
b=np.array([2,4,5,3]).reshape(2,2)
print(a)
print(b)
print(a@b)

[[21 34]
 [56 71]]
[[2 4]
 [5 3]]
[[212 186]
 [467 437]]


axis=0    column   
axis=1    row

In [ ]:
a=np.array([21,34,56,71]).reshape(2,2)
print(a)
print("-----------------")
print(a.max(axis=1))

[[21 34]
 [56 71]]
-----------------
[34 71]


In [ ]:
#max and min in an array
a=np.array([36,54,21,89,34])
print(a.max())
print(a.min())

89
21


In [ ]:
#max in the row of an array
a=np.array([21,34,56,71,32,55,77,89,39,10]).reshape(2,5)
print(a)
print("------------------")
print(a.max(axis=1))

[[21 34 56 71 32]
 [55 77 89 39 10]]
------------------
[71 89]


In [ ]:
a=np.array([21,34,56,71]).reshape(2,2)
b=np.array([2,4,5,3]).reshape(2,2)
print(a)
print("------------")
print(b)
print("-----------------")
print(np.vstack((a,b)))

[[21 34]
 [56 71]]
------------
[[2 4]
 [5 3]]
-----------------
[[21 34]
 [56 71]
 [ 2  4]
 [ 5  3]]


In [ ]:
a=np.array([21,34,56,71]).reshape(2,2)
b=np.array([2,4,5,3]).reshape(2,2)
print(a)
print("------------")
print(b)
print("-----------------")
print(np.stack((a,b),axis=0))
print("-----------------")
print(np.stack((a,b),axis=1))


[[21 34]
 [56 71]]
------------
[[2 4]
 [5 3]]
-----------------
[[[21 34]
  [56 71]]

 [[ 2  4]
  [ 5  3]]]
-----------------
[[[21 34]
  [ 2  4]]

 [[56 71]
  [ 5  3]]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print("After dstack")
print(np.dstack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#Splitting
a=np.arange(18).reshape(6,3)
print(a)
print("After Splitting")
np.vsplit(a,2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After Splitting


[array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#Splitting
a=np.arange(18).reshape(6,3)
print(a)
print("After Splitting")
np.vsplit(a,(5,2))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After Splitting


[array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([], shape=(0, 3), dtype=int64),
 array([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#Splitting
a=np.arange(18).reshape(6,3)
print(a)
print("After Splitting")
np.hsplit(a,(2,5))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After Splitting


[array([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13],
        [15, 16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([], shape=(6, 0), dtype=int64)]

In [ ]:
a=np.array([12,45,34,23,67,89,11,66,47,89,90,14]).reshape(3,4)
print(a)
print()

[[12 45 34 23]
 [67 89 11 66]
 [47 89 90 14]]
10


STATISTICS

In [ ]:
import numpy as np

In [ ]:
#MEAN,MEDIAN,STD,VAR
A=np.array([12,34,25,66,71,88])
print("MEAN :",np.mean(A))
print("MEDIAN :",np.median(A))
print("VARIANCE:",np.var(A))
print("STANDARD DEV :",np.std(A))

MEAN : 49.333333333333336
MEDIAN : 50.0
VARIANCE: 743.888888888889
STANDARD DEV : 27.274326552435515


TRIGONOMETRY

In [ ]:
A=np.pi
print(A)#radians

3.141592653589793


In [ ]:
np.rad2deg(A)

180.0

In [ ]:
B=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi/1])
print(B)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
print(np.rad2deg(B))

[ 45.  60.  90. 180.]


In [ ]:
C=np.array([0,30,45,60,90,120,180])
D=np.deg2rad(C)
print(D)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
np.sin(C)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [ ]:
np.cos(C)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [ ]:
np.tan(C)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [ ]:
np.arcsin(1)#sin^-1

1.5707963267948966

In [ ]:
np.arccos(1)#cos^-1

0.0

In [ ]:
np.arctan(1)#tan^-1

0.7853981633974483

In [ ]:
a=8
b=6
print(np.hypot(a,b))#hypotneuse

10.0


SEARCHING!

In [ ]:
A=np.array([90,3,45,21,34,90,21])
print(np.where(A==21))

(array([3, 6]),)


In [ ]:
A=np.array([90,3,45,21,34,90,21])
print(np.where(A%2==0))#even

(array([0, 4, 5]),)


In [ ]:
A=np.array([90,3,45,21,34,90,21])
print(np.where(A>25))#greater than 25

(array([0, 2, 4, 5]),)


In [ ]:
import numpy as np
A=np.array([1,2,3,4,5])
print(np.searchsorted(A,4))#3,21,34,45,90

3


LINEAR ALGEBRA AND UFUNC

In [ ]:
A=np.array([6,24,60,48,46])
B=np.array([3,1,5,9,4])
print(np.add(A,B))
print(np.subtract(A,B))

[ 9 25 65 57 50]
[ 3 23 55 39 42]


In [ ]:
print(np.divide(A,B))#quoitent
print(np.mod(A,B))#remiander
print(np.divmod(A,B))#both quo and rem

[ 2.         24.         12.          5.33333333 11.5       ]
[0 0 0 3 2]
(array([ 2, 24, 12,  5, 11]), array([0, 0, 0, 3, 2]))


In [ ]:
A=np.array([5,4,3,2,1])
print(np.sort(A))#sort
print(np.diff(A))#difference

[1 2 3 4 5]
[-1 -1 -1 -1]


SET FUNCTIONS

In [ ]:
A=np.array([1,2,3,4,5])
B=np.array([4,5,6,7,8,])
print(np.union1d(A,B))

[1 2 3 4 5 6 7 8]


In [ ]:
A=np.array([1,2,3,4,5])
B=np.array([4,5,6,7,8,])
print(np.setdiff1d(A,B))

[1 2 3]


In [ ]:
A=np.array([1,2,3,4,5])
B=np.array([4,5,6,7,8,])
print(np.intersect1d(A,B))

[4 5]


ROUNDING

In [ ]:
#trunc
A=np.trunc([-3.1666,3.6667])
print(A)

[-3.  3.]


In [ ]:
#fix
A=np.fix([-3.1666,3.6667])
print(A)

[-3.  3.]


In [ ]:
#around
A=np.around(3.1666,4)
print(A)

3.1666


In [ ]:
#floor
A=np.floor([-3.1666,3.6667])
print(A)

[-4.  3.]


In [ ]:
#ceil
A=np.ceil([-3.1666,3.1])
print(A)

[-3.  4.]


MORE FUNCTIONS

In [ ]:
A=np.array([3,4,16,19,10])
print(np.cumsum(A))

[ 3  7 23 42 52]


In [ ]:
A=np.array([3,4,16,19,10])
print(np.cumprod(A))

[    3    12   192  3648 36480]


In [ ]:
print(np.lcm(34,56))
print(np.gcd(445,655))

952
5


In [ ]:
A=np.array([45,65,30])
print(np.lcm.reduce(A))

1170


In [ ]:
A=np.array([45,65,30])
print(np.gcd.reduce(A))

5


In [ ]:
A=np.array([[1,2],[3,4]])
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


RANDOM

In [ ]:
from numpy import random as rd

In [ ]:
A=rd.rand()#n #default limit 0 to 0.99
print(A)

0.5119131989056418


In [ ]:
A=rd.rand(10)#default limit 0 to 0.99
print(A)

[0.41027528 0.56120362 0.34982722 0.12784874 0.80984838 0.66027017
 0.98446586 0.36249526 0.53410193 0.88434363]


In [ ]:
A=rd.randint(4)#randint(limit)==limit 0,1,2,3,4
print(A)

0


In [ ]:
A=rd.randint(50,size=6)#limit,size
print(A)

[35 36 30 15  1 44]


In [ ]:
A=rd.randint(50,size=(2,3))#limit,size
print(A)

[[29  8  1]
 [28 12  5]]


JOINS!

In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])
#1x4 + 2x5 +3x6
print(np.inner(A,B))

32


In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])
#1x4 , 1x5 ,1x6 : 2x4 , 2x5 ,2x6 : 3x4, 3x5 ,3x6
print(np.outer(A,B))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])
#det
print(np.cross(A,B))

[-3  6 -3]
